# Generated by Django 2.2.4 on 2020-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20201006_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='first_name', max_length=255),
            preserve_default=False,
        ),
    ]
